ALTER TABLE thesis
    ADD COLUMN created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_date DATETIME DEFAULT null;

ALTER TABLE seminar
    ADD COLUMN created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_date DATETIME DEFAULT null;
