name: Backend CI/CD using GitHub Actions & Docker
on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - 'frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 이전 steps 유지...

      # 프론트엔드 빌드
      - name: Install and Build Frontend
        env:
          CI: false
          NODE_ENV: production
          DISABLE_ESLINT_PLUGIN: true
        run: |
          cd frontend
          npm install
          npm run lint
          npm run prettier --check .
          npm run build

      # Docker 이미지 빌드 및 푸시
      - name: Docker build & push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
          # 백엔드 이미지 빌드 및 푸시
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
          
          # 프론트엔드 이미지 빌드 및 푸시
          cd ../frontend
          # nginx.conf 파일 생성
          echo "${{ secrets.NGINX_CONF }}" > nginx.conf
          
          docker build \
            --build-arg REACT_APP_GOOGLE_MAPS_API_KEY="${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}" \
            --build-arg REACT_APP_VIDEO_BASE_URL="${{ secrets.REACT_APP_VIDEO_BASE_URL }}" \
            -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
