name: Backend CI/CD using GitHub Actions & Docker

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - 'frontend/**'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 코드 체크아웃
      - uses: actions/checkout@v4

      # 백엔드 빌드 환경 설정 (JDK 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Docker 환경 변수 설정
      - name: Set up Docker Environment
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV

      # 백엔드 설정 파일 생성
      - name: Create backend configuration files
        run: |
          mkdir -p ./backend/src/main/resources
          cd ./backend/src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > application.yml

      # Gradle 설정
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      # 백엔드 빌드
      - name: Build Backend
        run: |
          cd backend
          chmod +x ./gradlew
          ./gradlew build -x test

      # Node.js 설정 (프론트엔드 빌드를 위한 Node.js 설치)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'  # LTS 버전으로 변경
          cache: 'npm'

      # 프론트엔드 빌드 - 수정된 부분
      - name: Install and Build Frontend
        env:
          CI: false
          NODE_ENV: production
          DISABLE_ESLINT_PLUGIN: true
          GENERATE_SOURCEMAP: false
        run: |
          cd frontend
          npm install
          # 필요한 모든 폴리필 설치
          npm install --save-dev stream-browserify buffer util assert crypto-browserify
          # craco 전역 설치
          npm install -g @craco/craco
          # craco.config.js 파일 생성
          echo "module.exports = {
            webpack: {
              configure: {
                resolve: {
                  fallback: {
                    crypto: require.resolve('crypto-browserify'),
                    stream: require.resolve('stream-browserify'),
                    buffer: require.resolve('buffer/'),
                    util: require.resolve('util/'),
                    assert: require.resolve('assert/')
                  }
                }
              }
            }
          };" > craco.config.js
          # package.json 수정하여 정확한 빌드 경로 지정
          sed -i 's/"build": ".*"/"build": "NODE_ENV=production CI=false node_modules\\/.bin\\/craco build"/' package.json
          # 빌드 실행 (메모리 한도 증가)
          export NODE_OPTIONS=--max_old_space_size=4096
          npm run build || npx craco build || node_modules/.bin/craco build || react-scripts build

      # Docker 이미지 빌드 및 푸시
      - name: Docker build & push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
          # 백엔드 이미지 빌드 및 푸시
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
          
          # 프론트엔드 이미지 빌드 및 푸시
          cd ../frontend
          docker build \
            --build-arg REACT_APP_GOOGLE_MAPS_API_KEY="${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}" \
            --build-arg REACT_APP_VIDEO_BASE_URL="${{ secrets.REACT_APP_VIDEO_BASE_URL }}" \
            -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # 서버에 docker-compose.yml 생성 및 실행
      - name: Deploy using Docker Compose
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SJ_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SJ_PRIVATE_KEY }}
          script: |
            # 서버 디렉토리로 이동
            mkdir -p ~/sejong-dibb
            cd ~/sejong-dibb
            
            # GitHub Secrets에서 docker-compose.yml 생성
            echo "${{ secrets.DOCKER_COMPOSE_YML }}" > docker-compose.yml
            
            
            # 기존 컨테이너 정리 및 새 배포 실행
            docker-compose down || true
            docker-compose pull
            docker-compose up -d
